name: E2E Facade Tests Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
 Windows_Test:
    runs-on: windows-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.4

      - name: Run tests
        continue-on-error: true
        run: >
          mvn clean test -Dtest="CreateNewNote.CreateNewNote,
          CreateNewUser.CreateNewUser,
          UpdateNote.UpdateNote,
          UpdateUserPassword.UpdateUserPassword"
          -D"allure.results.directory"="target/allure-results"

      - name: Generate Allure report
        run: mvn allure:report

      - name: Copy patch file to allure-maven-plugin folder
        run: cp src/main/resources/allow-file-access_open-report_chrome_windows.bat target/site/allure-maven-plugin

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure Report Windows
          path: "target/site/allure-maven-plugin"